site_name: Geospatial Environment - Development Draft

nav:
    - À propos du guide de l’EAG de l’ADS: indexFR.md
    - Contact: faqFR.md
    - Démarrage rapide: quickFR.md
    - Connexion: loginFR.md
    - Machine virtuelle: vmFR.md
    - Ingestion et stockage des données: pipelineFR.md
    - PostgreSQL + PostGIS: postgresqlFR.md
  # - Data Storage: storage.md
    - Écosystème ArcGIS:
        - ArcGIS Portal: portalFR.md
        - ArcGIS Pro: proFR.md
        - ArcGIS Insights: insightsFR.md
    - QGIS: qgisFR.md
    #- GeoServer: GeoServer.md
    #- COST vs FOSS : options.md
   # - Metadata:
       # - Standards: hnap.md
       # - GeoNetwork: geonetwork.md

    #- Publishing: publish.md
    - Multi-plateforme (ETAA/EAC):
        - ETAA: aawFR.md
        - EAC: caeFR.md
    #- Best Practices: bp.md
    - Centre de connaissances:
        - Introduction simple au SIG: introFR.md
        - Anaconda & Python: condaFR.md
        - SDMX: sdmxFR.md
        - Formation et tutoriels: resourcesFR.md
    


    

theme:
  name: material
  language: en
  features:
    - tabs
  palette:
    primary: green
    accent: red
  show_sidebar: true
  #logo:

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
copyright: © 2022 Statistics Canada; DAaaS GAE Early Adopter's Guide; Version 0.0.9
